### ISSUE TITLE
Contributions to the new repository

### ISSUE THREAD

**Issue by maxbachmann** [seatgeek/thefuzz#3]
@bigtoast I have two questions regarding contributions to this new repository:

1) The ReadMe of the old repository says `PRs and issues here will need to be resubmitted to TheFuzz`. In the past SeatGeek did not really have time to review PRs. Did this change? It would not make much sense to invest time on them, when it is already known, that they will probably never be reviewed.

2) Is there any plan up to which point the package should keep supporting Python2.7?

**Comment by bigtoast** [comment]
Hi @maxbachmann,

1. Not much has changed in that respect. We currently don't have the resources to invest much time in this project. While there is no planned work for the library, I will certainly review any PRs that are sent. 

2. There isn't a set plan. We do still have some legacy 2.7 code that uses this library. Even when that code is upgraded/replaced, 2.7 would probably still be supported purely because it is now and it also works fine in our 3.6-3.9 environments.
